### PR TITLE
Fix wysiwyg

### PR DESCRIPTION
**Pull request by chaubold**
which didn't work as noted in #195

### CODE REVIEW

**Comment by akreshuk** [comment]
LGTM, but haven't tested.

**Comment by FynnBe** [comment]
I'm not so happy with this yet... I'm getting:
```ERROR 2017-11-16 20:09:23,659 excepthooks 5608 15312 Traceback (most recent call last):
  File "C:\conda3\envs\ila\ilastik-meta\volumina\volumina\widgets\wysiwygExportOptionsDlg.py", line 463, in timerEvent
    next(self.exportloop)
  File "C:\conda3\envs\ila\ilastik-meta\volumina\volumina\widgets\wysiwygExportOptionsDlg.py", line 398, in loopGenerator
    coords = getter[pos]
TypeError: list indices must be integers or slices, not tuple
```

**Comment by chaubold** [comment]
Good catch, @FynnBe. It was indeed not working if you export a single slice. Works fine for me now,  could you try again, please?

**Comment by FynnBe** [comment]
works!

**Pull request merged**
