### PR TITLE
Made `ui` a package as apparently it is treated as one in `setup.py`

### PR DESCRIPTION
**Pull request by jakirkham**
This is where it is treated as a package ( https://github.com/ilastik/volumina/blob/master/setup.py#L29 ).

### CODE REVIEW

**Comment by jakirkham** [comment]
Failure appears to be due to an inability to download `tifffile` not an actual error with the code change.

**Comment by stuarteberg** [comment]
That directory contains no `.py` files; just `.ui` files.  Maybe the right thing to do is to just remove the offending line from `setup.py`?

**Comment by jakirkham** [comment]
Probably so. However, I don't know if there was a reason for it to be imported in the first place.

**Comment by jakirkham** [comment]
It may be that this is required for it to be copied over to site-packages in the first place.

**Comment by stuarteberg** [comment]
Hmm.  My guess is that the first entry in `package_data` should be deleted. (After all, `widgets.ui` isn't a package, as you pointed out.).  Instead, you should add `ui/*.ui` to the list of package data for the [`widgets` package](https://github.com/ilastik/volumina/blob/master/setup.py#L35).

**Comment by jakirkham** [comment]
This appears to install the `.ui` files correctly.

**Comment by stuarteberg** [comment]
OK, cool.  Thanks for giving it a try.

**Pull request merged**
