### PR TITLE
adds editability on/off for crop lines

### PR DESCRIPTION
**Pull request by ilastikdev**
needed in learning for training applet where editability must be turned off

### CODE REVIEW

**Comment by stuarteberg** [comment]
Maybe this would be a good opportunity to remove the `editableChanged` signal, since it doesn't appear to do anything.

**Comment by ilastikdev** [comment]
It is used to set editability and this may be done on a user toggle basis if I merge cropping and training applet (switching between training an dcropping modes), which is very likely, so I would leave it .

**Comment by stuarteberg** [comment]
I was confused because the text `editableChanged.emit` does not appear anywhere in the volumina source code.  But now I see it is called externally, in `tracking/annotations/annotationsGui.py`.  The existence of a signal that is emitted by external code, rather than by its own class, is not very idiomatic.  Can that be changed?

**Comment by ilastikdev** [comment]
done

**Comment by stuarteberg** [comment]
OK, thanks.

I guess I still don't understand why it is preferable to keep a copy of `CropExtentsModel._editable` stored in `CroppingMarkers`.  In the latter class, replacing all uses of

```python
if self._editable:
```

with this:

```python
if self.crop_extents_model.editable:
```

...would eliminate bookkeeping logic like `CroppingMarkers.onEditableChanged()`, and so on.  I could be missing something, though.  Is there a particular reason to store the `editable` flag twice?

**Comment by ilastikdev** [comment]
cropping markers is a parent of crop line so in the OO spirit I wanted to have self.editable instead of 
self.parent.crop_extents_model.editable

**Comment by ilastikdev** [comment]
@stuarteberg 
can we merge this?

**Comment by stuarteberg** [comment]
sure

**Pull request merged**
